### ISSUE TITLE
bug on firefox - words get multiple vectors

### ISSUE THREAD

**Issue by denik** [ronxin/wevi#1]
Seems to works fine for me on Chrome, but on Firefox, it looks like this (Note George twice):

<img width="1158" alt="screen shot 2015-12-06 at 22 59 59" src="https://cloud.githubusercontent.com/assets/86671/11615914/49471d8e-9c6d-11e5-9484-9c1baa5378e1.png">

**Comment by denik** [comment]
I noticed in the docs, it says there are known issues with FF. Feel free to close this if no plans to support FF.

**Comment by ronxin** [comment]
Yes... that is the very issue I observed in FF. Do you have any idea what is causing this? Might be an easy fix.

**Comment by denik** [comment]
Perhaps in this line unique() does not do what the name implies?

https://github.com/ronxin/wevi/blob/master/js/toyw2v.js#L104

> vocab = $.unique(vocab).sort()

See http://stackoverflow.com/a/8137873 which suggests sorting first and then calling unique().

**Comment by ronxin** [comment]
@denik Thanks for catching this!
